/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module angularMVCTypeScript {
    /** Generated from AngularMVCTypeScript.Features.Home.HomeViewModel **/
    export interface IHomeViewModel {
        helloAngular: string;
    }
}
